Daniel/inhibit device
globekeeper/dendrite pull request #43
Opened 2022-10-24 12:23 UTC by Danieloni1

2022-10-24 12:25 UTC, Danieloni1 commented
@PiotrKozimor 
Required adjustment for TOTP to work after adding the inhibit_device parameter.

2022-10-25 13:29 UTC, PiotrKozimor requested changes

2022-10-26 12:53 UTC, PiotrKozimor commented
💪

2022-10-26 12:54 UTC, PiotrKozimor approved these changes

2022-10-26 13:19 UTC, merged