🏗️ Support external auth provider login.
globekeeper/dendrite pull request #80
Opened 2023-12-24 16:17 UTC by Danieloni1

2023-12-24 16:23 UTC, Danieloni1 commented
@danpe I've organized the messy password login code, and added support for external auth provider (for GeoDome).
Still need to make the request to the external auth provider and continue with the existing logic in case I don't get 403, but I'll do that after I get the account in GeoDome and their API.

2023-12-27 11:46 UTC, danpe requested changes

2023-12-27 11:46 UTC, danpe commented on clientapi/routing/login.go
> +			loginFlows = append(loginFlows, flow{Type: authtypes.LoginTypeGeodome})
@Danieloni1 why appending Geodome twice?

2023-12-27 11:46 UTC, danpe commented on clientapi/auth/user_interactive.go
> +	ExternalAuthResp interface{} `json:"external_auth_response"`
@Danieloni1 do we need this as part of `UserInteractive`?

2023-12-27 11:46 UTC, danpe commented on clientapi/routing/login.go
> +	ExternalAuthResp interface{}     `json:"external_auth_response,omitempty"`
`external_response`

2024-02-21 09:34 UTC, closed without merging